/* 
 * CPSC-350-11-Database Design-2015FA BY PROF. LEE
 * GROUP - 17 - PROJECT 1 - PHASE 3
 * SRINIJA KATIKINENI
 */

 DROP TABLE AIRPORT cascade constraints;
 DROP TABLE AIRLINES cascade constraints;
 DROP TABLE FLIGHT cascade constraints;
 DROP TABLE FLIGHT_STOPS cascade constraints;
 DROP TABLE EMPLOYEE cascade constraints;
 DROP TABLE CUSTOMER cascade constraints;
 DROP TABLE SEAT_RESERVATION cascade constraints;
 DROP TABLE FLIGHT_LEG cascade constraints;

  /*  AIRPORT TABLE */

 CREATE TABLE AIRPORT
   (
      ARPORT_CODE VARCHAR2(10) NOT NULL ,
      ARPORT_NAME VARCHAR2(50) NOT NULL,
      ARPORT_CITY VARCHAR2(15) ,
      ARPORT_STATE VARCHAR2(20) ,
      ARPORT_COUNTRY VARCHAR2(25) ,
      CONSTRAINT PK_ARPORT PRIMARY KEY(ARPORT_CODE)
   );

 /* AIRLINES TABLE */
 CREATE TABLE AIRLINES
     (
        ARLINES_ID VARCHAR2(10) NOT NULL,
        ARLINES_NAME VARCHAR2(50),
        CONSTRAINT PK_ARLINES PRIMARY KEY(ARLINES_ID)
    );


 /* FLIGHT */
 
 CREATE TABLE FLIGHT
    (
        FLGT_NO     NUMBER(4) NOT NULL,
        FLGT_FARE   FLOAT(50)   NOT NULL,
        FLGT_SEATS  NUMBER(4),
        FLGT_AVAIL_DAY VARCHAR2(10) NOT NULL,
        ARLINES_ID  VARCHAR2(10) NOT NULL,
        CONSTRAINT PK_ PRIMARY KEY(FLGT_NO),
        CONSTRAINT FK_ARLINES_ID FOREIGN KEY (ARLINES_ID)
                      REFERENCES AIRLINES (ARLINES_ID)
   );



 /* EMPLOYEE */

  CREATE TABLE EMPLOYEE
        (
        EMP_NAME VARCHAR2(20),
        EMP_SSN NUMBER(4) NOT NULL,
        EMP_ID VARCHAR(6) NOT NULL,
        EMP_ALLOTED_FOR VARCHAR(8),
        FLGT_NO NUMBER(4),
        CONSTRAINT PK_EMP_ID PRIMARY KEY(EMP_ID),
        CONSTRAINT FK_EMP_FLGT FOREIGN KEY(FLGT_NO)
          REFERENCES FLIGHT(FLGT_NO)
     );



 /* CUSTOMER */

 CREATE TABLE CUSTOMER
   (
      CUST_ACC_NO NUMBER(5) NOT NULL,
      CUST_NAME VARCHAR2(20) NOT NULL,
      ADDRESS  VARCHAR2(50),
      CONTACT  VARCHAR2(10),
      PREFEREDSEAT VARCHAR2(20),
      PREFEREDMEAL VARCHAR2(10),
      CONSTRAINT PK_CUSTOMER PRIMARY KEY(CUST_ACC_NO)
    );


 /* FLIGHT_STOPS */

 CREATE TABLE FLIGHT_STOPS
    (
        FLGT_STOP_ID  VARCHAR(20) NOT NULL,
        FLGT_NO     NUMBER(4) NOT NULL,
        FLGT_STOP_DEP_ARPT_CODE  VARCHAR2(10),
        FLGT_STOP_SHD_DEP_TIME  TIMESTAMP,
        FLGT_STOP_ARR_ARPT_CODE  VARCHAR2(10),
        FLGT_STOP_SHD_ARR_TIME  TIMESTAMP,
        CONSTRAINT PK_FLGT_STOP PRIMARY KEY(FLGT_STOP_ID),
        CONSTRAINT FK_FLGT_STOP_FLGT  FOREIGN KEY (FLGT_NO)
              REFERENCES FLIGHT (FLGT_NO)
    );



 /* SEAT_RESERVATION */

 CREATE TABLE SEAT_RESERVATION
       (
            RESV_NO VARCHAR(15) NOT NULL,
            SEAT_NO VARCHAR(20) NOT NULL,
            DATE_OF_TRAVEL TIMESTAMP,
            BOOKING_FEE FLOAT(7) NOT NULL,
            TOTAL_FARE  FLOAT(8) NOT NULL,
            AVAILABLE_SEATS NUMBER(4),
            EMP_ID VARCHAR2(20) ,
            CUST_ACCNO NUMBER(5),
            CONSTRAINT PK_SEAT_RESERVATION PRIMARY KEY(RESV_NO),
            CONSTRAINT FK_SEAT_RES_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID),
            CONSTRAINT FK_SEAT_RES_CUST FOREIGN KEY (CUST_ACCNO) REFERENCES CUSTOMER(CUST_ACC_NO)
      );


  /* FLIGHT_LEG */

  CREATE TABLE FLIGHT_LEG
        (
            FLGT_LEG_ID VARCHAR(7) NOT NULL,
            FLGT_STOP_ID VARCHAR(20),
            SEAT_NO VARCHAR2(20),
            CONSTRAINT PK_FLGT_LEG PRIMARY KEY(FLGT_LEG_ID),
            CONSTRAINT FK_FLGT_LEG_FLGT_STOPS FOREIGN KEY(FLGT_STOP_ID)
            REFERENCES FLIGHT_STOPS(FLGT_STOP_ID)
      );

 /************************************************ USER DEFINED FUNCTIONS ***************************************************************/
 /*
  * NAME: GETEMPLOYEENAME
  * @DESCRIPTION: RETURN EMPLOYEE NAME FROM EMPLOYEE TABLE.
 */
  CREATE or REPLACE FUNCTION GETEMPLOYEENAME (FNO  in NUMBER)
       RETURN VARCHAR2 IS
           EMPLOYEENAME  VARCHAR2(50) := NULL;
        BEGIN
           SELECT EMP_NAME INTO EMPLOYEENAME
           FROM EMPLOYEE WHERE FLGT_NO=FNO;
          RETURN (EMPLOYEENAME);
        END;
    /

 --------------------------------------------------------------------------------------
 /*
  * NAME: GETCUSTOMERNAME
  * @DESCRIPTION: RETURN COMPANY NAME FROM CUSTOMER TABLE.
 */
  CREATE OR REPLACE FUNCTION GETCUSTOMERNAME(ACC_NO IN NUMBER)
     RETURN VARCHAR2 IS
         CUSTOMERNAME VARCHAR2(20)  := NULL;
        BEGIN
        SELECT CUST_NAME INTO CUSTOMERNAME FROM CUSTOMER WHERE CUST_ACC_NO=ACC_NO;
        RETURN (CUSTOMERNAME);
         END;
    /
 --------------------------------------------------------------------------------------
     /*
      * NAME: GETDEPARTUREAIRPORTCODE
      * @DESCRIPTION: RETURN DEPATURE AIRPORT CODE FROM FLIGHT_STOPS.
     */
 CREATE OR REPLACE FUNCTION GETDEPARPORT (FLGTNO in NUMBER)
    RETURN VARCHAR2 IS
       DEPARPORT VARCHAR2(50) := NULL;
    BEGIN
       SELECT FLGT_STOP_DEP_ARPT_CODE INTO DEPARPORT
       FROM FLIGHT_STOPS WHERE FLGT_NO = FLGTNO;
       RETURN DEPARPORT;
    END;
    /

 --------------------------------------------------------------------------------------
 /*
  * NAME: GETDAY
  * @DESCRIPTION: RETURN DAY OF FLIGHT JOURNEY  FROM  FLIGHT TABLE.
  */
CREATE OR REPLACE FUNCTION GETDAY (FLGTNO in NUMBER)
    RETURN VARCHAR2 IS
        DAY VARCHAR2(50) := NULL;
    BEGIN
       SELECT FLGT_AVAIL_DAY INTO DAY
       FROM FLIGHT WHERE FLGT_NO = FLGTNO;
       RETURN DAY;
    END;
   /

 --------------------------------------------------------------------------------------

  /*
  * NAME: GETFARE
  * @DESCRIPTION: RETURN FLIGHT FARE FROM FLIGHT TABLE.
  */
   CREATE OR REPLACE FUNCTION GETFARE (FLGTNO in NUMBER)
    RETURN VARCHAR2 IS
        FARE FLOAT(50) := NULL;
    BEGIN
       SELECT FLGT_FARE INTO FARE
       FROM FLIGHT WHERE FLGT_NO = FLGTNO;
       RETURN FARE;
    END;
   /

--------------------------------------------------------------------------------------
     /*
      * NAME: GETFLGTLEG
      * @DESCRIPTION: RETURN FLIGHT LEG NO FROM FLIGHT_LEG TABLE.
     */
      CREATE OR REPLACE FUNCTION GETFLGTLEG (SEATNO in VARCHAR2)
      RETURN VARCHAR2 IS
      LEGNO VARCHAR2(50) := NULL;
       BEGIN
       SELECT FLGT_LEG_ID INTO LEGNO
       FROM FLIGHT_LEG WHERE SEATNO = SEATNO;
      RETURN LEGNO;
      END;
    /

 --------------------------------------------------------------------------------------
 DROP FUNCTION GETEMPLOYEENAME;
 DROP FUNCTION GETCUSTOMERNAME;
 DROP FUNCTION GETDEPARPORT;
 DROP FUNCTION GETDAY;
 DROP FUNCTION GETFARE;
 DROP FUNCTION GETFLGTLEG;