/* 
 * CPSC-350-11-Database Design-2016 BY PROF. LEE
 * GROUP - 17 - PROJECT 1 - PHASE 3
 * SRINIJA KATIKINENI-1004775
 */


DROP TABLE AIRPORT cascade constraints;
DROP TABLE AIRLINES cascade constraints;
DROP TABLE FLIGHT cascade constraints;
DROP TABLE FLIGHT_STOPS cascade constraints;
DROP TABLE EMPLOYEE cascade constraints;
DROP TABLE CUSTOMER cascade constraints;
DROP TABLE SEAT_RESERVATION cascade constraints;
DROP TABLE FLIGHT_LEG cascade constraints;



DROP FUNCTION GETEMPLOYEENAME;
DROP FUNCTION GETCUSTOMERNAME;
DROP FUNCTION GETDEPARTUREAIRPORTCODE;
DROP FUNCTION GETDAY;
DROP FUNCTION GETFARE;
DROP FUNCTION GETFLGTLEG;

